Shippable/reqExec

- build.sh
- config.py
- main.py
- package.sh
Closes #3 
Closes #4 
Closes #5 
Closes #6
> Update all references to cexec

- Dockerfile
- Makefile
- README.md
> Use Docker to build reqExec binaries

- build.sh
- package.sh
https://github.com/Shippable/reqExec/issues/10
> Remove architecture specific references

- config.py
- executor.py
- main.py
- shippable_adapter.py
Has no error handling. Just a very minimal executor. This will be enhanced later.
https://github.com/Shippable/reqExec/issues/14
> Add base executor

- executor.py
- main.py
https://github.com/Shippable/reqExec/issues/16
> Handle script success, failure markers

- config.py
- executor.py
- main.py
https://github.com/Shippable/reqExec/issues/16
> Add threaded execution and timer based console flush

- config.py
- executor.py
> Run script in context of build directory

- executor.py
https://github.com/Shippable/reqExec/issues/22
> Unset LD_LIBRARY_PATH to make script is system libraries

- .pylintrc
- config.py
- executor.py
- main.py
- shippable_adapter.py
Fixes https://github.com/Shippable/reqExec/issues/24
Fixes https://github.com/Shippable/reqExec/issues/27
Fixes https://github.com/Shippable/reqExec/issues/28
Fixes https://github.com/Shippable/reqExec/issues/29
> Better error handling, logs

- Dockerfile
- README.md
- build.sh
https://github.com/Shippable/pm/issues/9568
> Update README.md to build in container

- README.md
- build.sh
- package/x86_64/macOS_10.12/package.sh
https://github.com/Shippable/reqExec/issues/36
> Add a package script for x86_64 macOS_10.12

- package/aarch64/Ubuntu_16.04/package.sh
https://github.com/Shippable/reqExec/issues/39
> Fix aarch64/Ubuntu_16.04/package.sh

- executor.py
https://github.com/Shippable/reqExec/issues/42
> Assume failure by default

- README.md
- package/x86_64/WindowsServer_2016/package.ps1
https://github.com/Shippable/reqExec/issues/44
>  adds scripts to build reqExec for windows

- executor.py
Fixes https://github.com/Shippable/reqExec/issues/47
> Return early if Popen fails

- package/x86_64/Ubuntu_14.04/package.sh
https://github.com/Shippable/reqExec/issues/51
> adds packaging script for reqExec for x86_64 ubuntu 14.04

- package/x86_64/CentOS_7/package.sh
https://github.com/Shippable/reqExec/issues/53
> adds pakage.sh script for x86_64/CentOS_7

- package/aarch64/Ubuntu_16.04/package.sh
trying to package reqExec on host. this installs virtualenv on host
> install virtualenv

- executor.py
https://github.com/Shippable/reqExec/issues/60
Verified on 
1. Windows Server 2016
1. Ubuntu 16.04
> uses REQEXEC_SHELL variable

- executor.py
https://github.com/Shippable/reqExec/issues/62
When using the reqExec that comes in with `drydock/reqproc:master` => job is success 
https://rcapp.shippable.com/github/sample-organisation/jobs/emergency-2/builds/5a621a554188c8050093a899/console
When I built the code in master of reqExec => job seem to show the expected error
https://rcapp.shippable.com/github/sample-organisation/jobs/emergency-2/builds/5a6221074188c8050093a89a/console
When I built the code in this PR => job seem to be success 
https://rcapp.shippable.com/github/sample-organisation/jobs/emergency-2/builds/5a6221b4c275940500d143cd/console
> uses get to access dict

- package/aarch32/Ubuntu_16.04/package.sh
- shippable.yml
https://github.com/Shippable/reqExec/issues/75
https://github.com/Shippable/reqExec/issues/77
https://github.com/Shippable/reqExec/issues/78
> adds support for aarch32

- executor.py
> Revert "Remove length based console flushing"

- .pylintrc
- config.py
- executor2.py
- main.py
https://github.com/Shippable/reqExec/issues/82
> Add file based consoles handling

- config.py
- executor2.py
https://github.com/Shippable/reqExec/issues/82
> Fix parsing of envs, add hidden notice

- executor2.py
It shows up unnecessarily sometimes otherwise.
https://github.com/Shippable/reqExec/issues/82
> Close the notice group

- executor2.py
> Set post_logs only when there's something to post
